### PR TITLE
feat: export `normalizePrivateKey`

### PR DESCRIPTION
**Pull request by SergeyVolynkin**
Hi @paulmillr, thank you for the effort you put into this library!

Would it be possible to export `normPrivKey` on the `npm` package?
We plan to use it for account derivation logic with `grindKey` which does not always result in a padded private key.

### CODE REVIEW

**Comment by paulmillr** [comment]
Can you export it as normalizePrivateKey?

**Comment by SergeyVolynkin** [comment]
@paulmillr renamed the exported function to `normalizePrivateKey` in e9e1bb7

Please let me know if you'd prefer the export alias solution instead
```
export { normPrivateKey as normalizePrivateKey };
function normPrivateKey(privKey: Hex): string {
  return u.bytesToHex(ensureBytes(privKey)).padStart(64, '0');
}
```

**Comment by paulmillr** [comment]
Please also add some kind of test. It can be basic, like, 1-3 lines of code.

And fix failing CI.

**Comment by SergeyVolynkin** [comment]
Thank you @paulmillr 
1. Added test
2. Opened https://github.com/paulmillr/scure-starknet/pull/11 to fix CI, as it fails for unrelated change (started to fail after TS upgrade to `v5.5`

**Pull request merged**
